### ISSUE TITLE
Documentation missing ?

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-zapier#1]
Hello guys,

Would it be possible to have a longer documentation of how to set it up in Zapier, which contact fields can be synced, etc ?

N.

**Comment by escopecz** [comment]
Sure. Although many fields are dynamic in Mautic. So we can document only the internal fields. Is that OK? Isn't faster to create the Zap and see the fields available for your Mautic instance for yourself than to read the documentation?

**Comment by npracht** [comment]
But does the custom fields goes in Zapier also ?
I mean John, it is always more comfortable for your users to follow your steps than just discovering Zapier.
For most of them they are not familiar with zapier. Kind a step by step documentation with sceenshots would be very useful.

**Comment by escopecz** [comment]
I personally rather use the product first and look into the docs only when I get stuck. But I agree that good detailed documentation is always better. Can you push a PR with it? I'm having hard time to push this Zapier integration through the review process.

**Comment by npracht** [comment]
That's precisely what i'm looking for... i cannot do it :D

**Comment by escopecz** [comment]
Where in the process do you get stuck?

**Comment by escopecz** [comment]
BTW [the documentation](https://github.com/mautic/mautic-zapier#mautic-zapier-integration) has been improved. Let me know if something confuses you still.

**Comment by npracht** [comment]
This is great !
