### ISSUE TITLE
Error #500 (zapier error) when connecting to zapier

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic-zapier#10]
Hi, Zapier is giving me an error #500 when I try to establish a connection for a new zap (wizard).

Using Mautic 2.13.1
I cleared cache
Even created a new user just in case...
(And yes, cleared cache again)

Any idea what can be causing this?

Please note it's not an apache error 500 but a Zapier error #500

**Comment by YosuCadilla** [comment]
Tried to use it logged in and logged out of Mautic, really don't know what else to try...

![untitled-2](https://user-images.githubusercontent.com/29537089/41817677-28385002-77a0-11e8-92c3-ac246309ceaf.png)

![untitled-1](https://user-images.githubusercontent.com/29537089/41817681-3c014328-77a0-11e8-812b-5e4c925cabf8.jpg)

**Comment by YosuCadilla** [comment]
This happens while trying to connect FB leads to Mautic. After a successful connection to Facebook, when Zapier is trying to connect to Mautic.

**Comment by YosuCadilla** [comment]
Tried with 3 different accounts, all of them administrators.

**Comment by escopecz** [comment]
What is the error in Mautic's logs?

**Comment by YosuCadilla** [comment]
There's nothing on Mautic log nor Apache log, seems to be a Zapier error #500 nothing to do with apache's error 500 it would seem

**Comment by YosuCadilla** [comment]
Not sure if Zapier did something on their end (sent a couple support requests) or I changed something in my Mautic instance, anyway, I got a successful connection this morning.

**Comment by escopecz** [comment]
I can see in your screenshots that Zapier is reporting classic Mautic's 500 message. So there had to be some error message recorded in the Mautic's log. Check them out next time. I'm glad it's working for you now!

**Comment by YosuCadilla** [comment]
Thank you John.
I think my problem is related to permissions, every time I do clear:cache I have to chown + chmod afterwards or I get some errors when Mautic tries to create/write to files.

Yes there where 2 permissions related errors in Mautic log that I disestimated (and clearly should not have).

**Comment by escopecz** [comment]
Then be sure you run the clear:cache command as the web user, not root. Or do `rm -rf app/cache/prod/*` which will only delete the files and Mautic will create them itself on next request.

**Comment by YosuCadilla** [comment]
Aha! OK thank you very, very much!

**Comment by campiotto** [comment]
I was having the same problem and this worked for me.
`chown www-data:www-data app/cache/prod/`
`rm -rf app/cache/prod/*`

Thank you guys!
