### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by virgilwashere** [mautic/mautic-zapier#15]
@escopecz I see you bumped `package.json` to `2.12`, but the repo doesn't have a matching 🚀 Release, 🏷Tag, or 📝`CHANGELOG.md` entry 😢 

Also, `dependabot` ??  Or `greenkeeper`.  Use the free services.

V

Close me off whenever. 👋

**Comment by escopecz** [comment]
https://github.com/mautic/mautic-zapier/releases/tag/2.1.2 is that better?

Please submit a pull request if you wish to improve things 👋
