### ISSUE TITLE
ERROR | 404 | Auth Failed

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic-zapier#2]
Hello,

I'm having an issue with zapier integration.

In Zapier's Connect an Account dialogue, after entering in the username, password and URL and clicking "Yes, Continue" I am presented with this error:

"We hit an error adding your new account
authorization failed: Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!"

I have confirmed the the API and basic auth is enabled, and I'm running SSL.

My server environment is:
Mautic 2.9.2
Nginx
Zapier Mautic v1.0.2 (have also tried all other Mautic versions in Zapier when configuring new connection, no success)

Has anyone else experienced anything similar? (edited)

Nginx access.log yields the following:
34.227.148.39 - zapieruser [26/Aug/2017:20:59:13 +0200] "GET /api/contacts?limit=1&minimal=1 HTTP/1.1" 200 414 "-" "Zapier"
52.71.88.164 - zapieruser [26/Aug/2017:20:59:15 +0200] "GET /api/contacts?limit=1&minimal=1 HTTP/1.1" 200 414 "-" "Zapier"

Found error when attempting to access the API URL in a browser.
{
errors: [
{
message: "API authorization denied.",
code: 401,
type: "access_denied"
}
],
error: "access_denied",
error_description: "API authorization denied. (`error` and `error_description` are deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"
}

i assume this is the same error being returned to Zapier.

**Comment by vexersa** [comment]
UPDATE:

This error appears in logs: 

PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/mautic/app/cache/prod/classes.php on line 3710" while reading response header from upstream, client: 34.207.73.245, server: XXXX.XXXX.com, request: "POST /api/contacts/new HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "XXXX.XXXX.com"

TRIED: 
Increasing PHP mem limit from 256M to 512M, same error persists

**Comment by vexersa** [comment]
UPDATE: 

Tried fresh install Mautic instance and same problem exists. 

Nginx error log:
Empty.

Access log:
Zapier's attempt at connecting to Mautic is logged. 

Mautic log:
N/A

**Comment by vexersa** [comment]
Could this be related?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414

**Comment by escopecz** [comment]
What is the URL you are filling in?

**Comment by vexersa** [comment]
@escopecz, are you referring to the URL when adding the credentials to Zapier? 

If so, any of these Mautic instances produce the same error:

- http://mautic.thepaleodiet.co.za

- https://mautic.theindividual.store

- https://mautic.youfashionista.store

All are on the same server.

**Comment by escopecz** [comment]
Those look correct. Can you try clear their caches by removing content  of the `app/cache/`directory and try again?

Do you use queues on for webhooks or immediate send? How many custom fields do you have?

**Comment by vexersa** [comment]
Clearing app/cache seemed to have worked. 

I use instant send. Many custom fields which are all working. 

Thanks :)

**Comment by theperfectwill** [comment]
@escopecz 

Not sure if many other people are having issues with this, but maybe you can consider noting this on  description page to clear the /app/cache directory?

This is the only thing that worked for me over the last 2 days. I took a chance to browse the closed issues after nothing else from the forum I found, etc. worked.

But, finally!

Thanks for this work. 💯  Everything seems to be working flawless now. 🥇

**Comment by diegodorgam** [comment]
Just for curiosity, why this error occurs ? what does it have in the app/cache that is related to the login?

**Comment by tsnork** [comment]
Sorry, but why is this issue closed? This is still a problem in 2019 and the workaround of clearing the cache still works.

**Comment by jvazservices** [comment]
tb estou tendo os memsmos problemas, vou ver se limpar o chache funciona.

**Comment by MyluckMomentum** [comment]
I'm having same error on v2.15.1. Please help me. :(

**Comment by karelvysinka** [comment]
This working for me:
https://innotiom.com/mautic-zapier-integration/

Update your Mautic settings
As described here, you’ll need to enable Basic Authentication to use the Zapier integration. To do so, follow these steps:

Go to Mautic Settings > Configuration > API Settings
Set API enabled? to Yes
Set Enable HTTP basic auth? to Yes
Make sure to save your changes.

**Comment by BenJackGill** [comment]
I'm still getting this error in 2020 with latest version.

Clearing `app/cache` worked for me.

This needs to be clearly stated in the help docs :) I just wasted 4 hours trying to fix.

**Comment by Vishalyzd** [comment]
As mentioned https://github.com/mautic/mautic-documentation/pull/44 why can't we have an automated fix for clearing the cache's up in the next update?

Also, I'm trying to connect zap with mautic but says the same error even after clearing the cache.
