### ISSUE TITLE
Mautic Zapier Integration is Only For ACQUIA CAMPAIGN STUDIO?

### ISSUE THREAD

**Issue by iamthebruce** [mautic/mautic-zapier#20]
I'm trying to integrate my Mautic installation with Zapier and the Zapier support reps have commented that the Mautic Zapier integration only works with instances hosted at mautic.net with ACQUIA CAMPAIGN STUDIO. This doesn't seem to fit the spirit of an open source project and it seems wrong to me, but I wanted to open an issue to just to make sure before pursuing the issue further with Zapier.

<img width="935" alt="Screen Shot 2021-03-10 at 12 40 48 PM" src="https://user-images.githubusercontent.com/79641608/110655736-127e1200-819e-11eb-9d1b-848be8479de4.png">

**Comment by escopecz** [comment]
That's not true. The full URL must be configured when you are creating the Zap. It works for open source instances of Mautic as well as for the Acquia's Campaign Studio instances. 

![Screen Shot 2021-03-11 at 17 28 04](https://user-images.githubusercontent.com/1235442/110820396-57ce3c80-828f-11eb-8ea5-6fcbe663fb69.png)

What is the issue with your Zapier configuration? Do you get any error?

**Comment by iamthebruce** [comment]
Yes, the error I was getting was the following:
<img width="619" alt="mautic error" src="https://user-images.githubusercontent.com/79641608/111014065-dd7de500-8380-11eb-9c16-73a64af9dc93.png">
I contacted Zapier support, but as you can see they were badly uninformed. The problem was the Mautic cache. I found on a forum that deleting the Mautic cache was the way to solve the issue. I deleted everything in the cache folder via FTP and then Zapier was able to connect properly.
<img width="729" alt="resolve" src="https://user-images.githubusercontent.com/79641608/111014106-07cfa280-8381-11eb-985c-c5a765daba01.png">
