### ISSUE TITLE
impossible to map select type field

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-zapier#3]
# Issue
I created a `select` typed custom contact field, and this field is not coming to the Zapier mapping page.

**Comment by kuzmany** [comment]
This works for If I go back and Re-test step 1.
Zapier recommend it as last option. See screenshot
Zapier store contact fields and you need refresh it in step 1.

![image](https://user-images.githubusercontent.com/462477/31897459-bf4e7b3c-b816-11e7-8354-1ec19f80f935.png)
