### ISSUE TITLE
error sync mautic zapier

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic-zapier#4]
Hello,

I got this error with a zap from kontest to mautic:
Dev app App51025API (Mautic) throttled (100 script executions per 30 seconds), contact support.

The zapier support told us that they cannot help us as this integration with mautic is still a beta.

Can you tell me what is it ? @escopecz 
Thanks a lot
Johan

**Comment by escopecz** [comment]
HI, it's a [Zapier limit](https://zapier.com/help/troubleshooting/#zapier-throttling). The app is still getting through the review process by Zapier team to get the Mautic integration out of beta and the ball is on their side right now. There is nothing we can do about that limit.
