### ISSUE TITLE
Zapier with webinarjam

### ISSUE THREAD

**Issue by mrkingsleyobi** [mautic/mautic-zapier#5]
I tried to integrate webinarjam with mautic using zapier it game me an error:
This is the error:
errors:
1: message:	Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!
code:	404
type:	
error:
message:	Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)
code:	404

How do I get around this

**Comment by escopecz** [comment]
Make sure you [prepared your Mautic](https://github.com/mautic/mautic-zapier#prepare-your-mautic) and then [clear the Mautic's cache](https://mautic.org/docs/en/tips/troubleshooting.html#1-clear-the-cache) as it sometimes happens that API calls return 404 at first.
