### ISSUE TITLE
Zapier > Mautic update overwrite/delete the data in Mautic

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic-zapier#6]
Hi there, I'm trying to optimise my email flow in Gmail with Mautic and Zapier. Basically what I want like to do is:
- When I get an answer from a potentiel leads, I label it in Gmail "lead"
- Then Zapier read in the label and add a tag "lead" in Mautic
- Then the Mautic contact is updated with the new tag and goes in the right segment.

I've done tests, it's adding the tag, but based on the email address that is already in Mautic, it removes the firtname and lastname and also the Preferred Locale etc... It seems that the update is overwriting some of the data randomly. For example CompanyName remains.

I was expecting the Zap to referrer to the right contact in Mautic via the email address only, and add the tag, nothing else.

Here is the current config in Zapier

![screenshot 2018-02-07 17 06 10](https://user-images.githubusercontent.com/4152261/35928819-644bb76a-0c2e-11e8-8639-bc5b6c83d5ee.png)
![screenshot 2018-02-07 17 08 22](https://user-images.githubusercontent.com/4152261/35928820-6470701e-0c2e-11e8-8b80-398bb01ee55e.png)

**Comment by drimlike** [comment]
Hello, just wondering if there was any solution please? Do you also have the issue? Happy to help in the debug process :)

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic-zapier/releases/tag/2.0.2. All Zaps on 2.0.1 will be migrated automatically in few minutes.
