### ISSUE TITLE
Error when i try to connect zapier with mautic

### ISSUE THREAD

**Issue by eduardorph** [mautic/mautic-zapier#9]
Hi,

I have a mautic installation in a digital ocean droplet with Apache server and ubuntu 16.04

I follow some tutorials to integrate zapier with mautic, but i always see the message bellow:

I already activate the API enabled and Enable HTTP basic auth to YES

"authentication failed: The URL you provided (https://loudmonitor.ga) is not the base URL of a Mautic instance"

Can you help me?

**Comment by escopecz** [comment]
Did you try to access that URL you have filled in?
![screen shot 2018-05-23 at 09 11 13](https://user-images.githubusercontent.com/1235442/40408880-54d9c726-5e69-11e8-9ce5-7c15448860bd.png)
